//Project urls
const POSTTASKADD = "projectList/save";
const GETPROJECT = "project/name"
const GET_RESEARCHED_DOC = "researchQuotation/view"

const PUT_PROMOTE_RESEARCH = "research/quotation/edit/"

// Management Approved

const GET_MANAGEMENT_APPROVED_PROJECTS = "researchDevelopment/view/"
const PUT_ASSIGN_PROJECT = "researchDevelopment/edit/"
const PUT_CHANGE_ASSIGNPROJECT_STATUS = "research/development/details/edit/"


// Development in Research Urls 

const GET_DEV_COMPLETED = "researchDevelopmentFile/view/"
const PUT_DEV_STATUS_CHANGE = "research/project/details/edit/"
const GET_APPROVED_PROJECT = "quotation/view/client/"
const PUT_APPROVEDPROJECT_STATUSCHANGE = "quotation/details/edit/"
const PUT_DEV_ASSIGNEE = "researchDevelopmentFile/edit/"


// Approved R & D 

const GET_APPROVED_R_AND_D = "projectAssigning/view/"
const PUT_CHANGE_APPROVED_R_AND_D_STATUS = "project/details/edit/"
const PUT_ASSIGN_PROJECT_DEPT_PL_DEV = "projectAssigning/edit/"

// All Emp And Trainee Under Department

const GET_ALL_EMP_AND_TRAINEE_UNDER_DEPT = "department/role/project/"

// Projects For Testing

const GET_ALL_PROJECTS_FOR_TESTING = "projectDocumentation/view/"
const PUT_ASSIGN_PL_FOR_TESTING = "projectDocumentation/edit/"
const PUT_APPROVING_TO_TESTING = "project/file/details/edit/"
const GET_ALL_APPROVED_PROJECTS_FOR_TESTING = "testing/view/"
const PUT_APPROVING_TESTING_TO_MANAGEMENT = "testingDocumentation/status/edit/"
const PUT_ASSIGN_PL_AND_DEPT_FOR_TESTING = "testing/edit/"
const PUT_APPROVE_TO_TESTING = "testing/details/edit/"
const GET_ALL_TESTING_DOCUMENTS = "testingDocumentation/view"

const GET_ALL_TESTED_APPROVED_DOCUMENTS = "testingDocumentation/view/accepted"
const PUT_ASSIGNING_PL_AFTER_TESTING = "testingDocumentation/edit/"

// Hosting

const GET_ALL_PROJECTS_FOR_HOSTING = "hosting/view/table"
const PUT_ASSIGN_PL_AND_DEPT_FOR_HOSTING ="hosting/edit/"
const GET_ALL_HOSTING_DOC = "hostingDocumentation/view"
const PUT_APPROVE_HOSTING = "hosting/details/edit/"
const PUT_APPROVED_HOSTED_DOC = "hostingDocumentation/status/edit/"
const GET_APPROVED_HOSTED_DOC = "hostingDocumentation/view/accepted"


export const RANDDURLS = {
  //Project urls
  POSTTASKADD: POSTTASKADD,
  GETPROJECT: GETPROJECT,
  GET_RESEARCHED_DOC: GET_RESEARCHED_DOC,

  PUT_PROMOTE_RESEARCH: PUT_PROMOTE_RESEARCH,

  // Management Approved

  GET_MANAGEMENT_APPROVED_PROJECTS: GET_MANAGEMENT_APPROVED_PROJECTS,
  PUT_ASSIGN_PROJECT: PUT_ASSIGN_PROJECT,
  PUT_CHANGE_ASSIGNPROJECT_STATUS: PUT_CHANGE_ASSIGNPROJECT_STATUS,

  // Development in Research

  GET_APPROVED_PROJECT: GET_APPROVED_PROJECT,
  PUT_APPROVEDPROJECT_STATUSCHANGE: PUT_APPROVEDPROJECT_STATUSCHANGE,

  GET_DEV_COMPLETED: GET_DEV_COMPLETED,
  PUT_DEV_STATUS_CHANGE: PUT_DEV_STATUS_CHANGE,
  PUT_DEV_ASSIGNEE: PUT_DEV_ASSIGNEE,

  GET_APPROVED_R_AND_D: GET_APPROVED_R_AND_D,
  PUT_CHANGE_APPROVED_R_AND_D_STATUS : PUT_CHANGE_APPROVED_R_AND_D_STATUS ,
  PUT_ASSIGN_PROJECT_DEPT_PL_DEV : PUT_ASSIGN_PROJECT_DEPT_PL_DEV ,
  
  GET_ALL_EMP_AND_TRAINEE_UNDER_DEPT : GET_ALL_EMP_AND_TRAINEE_UNDER_DEPT,

  GET_ALL_PROJECTS_FOR_TESTING : GET_ALL_PROJECTS_FOR_TESTING ,
  PUT_ASSIGN_PL_FOR_TESTING : PUT_ASSIGN_PL_FOR_TESTING ,
  PUT_APPROVING_TO_TESTING : PUT_APPROVING_TO_TESTING ,
  GET_ALL_APPROVED_PROJECTS_FOR_TESTING : GET_ALL_APPROVED_PROJECTS_FOR_TESTING,
  PUT_ASSIGN_PL_AND_DEPT_FOR_TESTING : PUT_ASSIGN_PL_AND_DEPT_FOR_TESTING ,
  PUT_APPROVE_TO_TESTING : PUT_APPROVE_TO_TESTING,
  GET_ALL_TESTING_DOCUMENTS : GET_ALL_TESTING_DOCUMENTS,
  PUT_ASSIGNING_PL_AFTER_TESTING : PUT_ASSIGNING_PL_AFTER_TESTING,
  PUT_APPROVING_TESTING_TO_MANAGEMENT : PUT_APPROVING_TESTING_TO_MANAGEMENT ,

  GET_ALL_TESTED_APPROVED_DOCUMENTS : GET_ALL_TESTED_APPROVED_DOCUMENTS,

// Hosting 

  GET_ALL_PROJECTS_FOR_HOSTING : GET_ALL_PROJECTS_FOR_HOSTING ,
  PUT_ASSIGN_PL_AND_DEPT_FOR_HOSTING : PUT_ASSIGN_PL_AND_DEPT_FOR_HOSTING,
  PUT_APPROVE_HOSTING : PUT_APPROVE_HOSTING ,
  PUT_APPROVED_HOSTED_DOC : PUT_APPROVED_HOSTED_DOC ,
  GET_ALL_HOSTING_DOC : GET_ALL_HOSTING_DOC,
  GET_APPROVED_HOSTED_DOC : GET_APPROVED_HOSTED_DOC ,
  
}